site_name: Darksky blog
strapline:
logo: static/darksky-light-bg.svg
logo_size: [200,127]
background: none
base_url: https://darksky.io/

site_description: >
  Darksky.io is an Electronics, Electrical and Software consultancy based in
  the UK. It is also an invite-only discussion community, founded in 2010.

extra_links:
  - ["Forum","https://boards.darksky.io/"]
  - ["Chat","https://chat.darksky.io/"]

copyright_msg: >
  Darksky.io Limited unless otherwise noted. All rights reserved.

copyright_from: 2010

footer_msg: >
  Company Registered in England &amp; Wales. Company No. 10044342.

discourse_url: "https://boards.darksky.io"
discourse_api_user: naggie
discourse_api_key: <lolno>
discourse_category: blog
import_to_discourse: True

output_dir: /srv/http/darksky.io/public/blog
# articles by discourse users from external websites
# will be written to discourse for discussion
feed_import:
  - url: "https://jamesreuss.co.uk/index.xml"
    username: jimjibone

  - url: "https://callanbryant.co.uk/rss/"
    username: naggie

  - url: "https://frillip.com/rss/"
    username: frillip
