url: "https://boards.darksky.io"
api_user: naggie
api_key: <redatacted>
category: blog
output_dir: /srv/http/darksky.io/public/blog
# articles by discourse users from external websites
# will be written to discourse for discussion
feed_import:
  - url: "https://jamesreuss.co.uk/index.xml"
    username: jimjibone

  - url: "https://callanbryant.co.uk/rss/"
    username: naggie

  - url: "https://frillip.com/rss/"
    username: frill

