url: "https://boards.darksky.io"
api_user: naggie
api_key: <redatacted>
category: blog
build_dir: /srv/http/darksky.io/public/blog
# articles by discourse users from external websites
# will be written to discourse for discussion
import:
  - class: Feed
    url: "http://jamesreuss.co.uk/index.xml"
    username: jimjibone

  - class: Feed
    url: "https://callanbryant.co.uk/rss/"
    username: naggie

  - class: Feed
    url: "https://frillip.com/rss/"
    username: frill

